using System;
using Vectordrawing;
using System.Collections.Generic;
using Godot;

namespace Vectordrawing;

class GlyphNames
{
    static string raw = 
"""
0041;ACapital;LATIN CAPITAL LETTER A
00C6;AECapital;LATIN CAPITAL LETTER AE
01FC;AEacuteCapital;LATIN CAPITAL LETTER AE WITH ACUTE
00C1;AacuteCapital;LATIN CAPITAL LETTER A WITH ACUTE
0102;AbreveCapital;LATIN CAPITAL LETTER A WITH BREVE
00C2;AcircumflexCapital;LATIN CAPITAL LETTER A WITH CIRCUMFLEX
00C4;AdieresisCapital;LATIN CAPITAL LETTER A WITH DIAERESIS
00C0;AgraveCapital;LATIN CAPITAL LETTER A WITH GRAVE
0391;AlphaCapital;GREEK CAPITAL LETTER ALPHA
0386;AlphatonosCapital;GREEK CAPITAL LETTER ALPHA WITH TONOS
0100;AmacronCapital;LATIN CAPITAL LETTER A WITH MACRON
0104;AogonekCapital;LATIN CAPITAL LETTER A WITH OGONEK
00C5;AringCapital;LATIN CAPITAL LETTER A WITH RING ABOVE
01FA;AringacuteCapital;LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
00C3;AtildeCapital;LATIN CAPITAL LETTER A WITH TILDE
0042;BCapital;LATIN CAPITAL LETTER B
0392;BetaCapital;GREEK CAPITAL LETTER BETA
0043;CCapital;LATIN CAPITAL LETTER C
0106;CacuteCapital;LATIN CAPITAL LETTER C WITH ACUTE
010C;CcaronCapital;LATIN CAPITAL LETTER C WITH CARON
00C7;CcedillaCapital;LATIN CAPITAL LETTER C WITH CEDILLA
0108;CcircumflexCapital;LATIN CAPITAL LETTER C WITH CIRCUMFLEX
010A;CdotaccentCapital;LATIN CAPITAL LETTER C WITH DOT ABOVE
03A7;ChiCapital;GREEK CAPITAL LETTER CHI
0044;DCapital;LATIN CAPITAL LETTER D
010E;DcaronCapital;LATIN CAPITAL LETTER D WITH CARON
0110;DcroatCapital;LATIN CAPITAL LETTER D WITH STROKE
2206;Delta;INCREMENT
0045;ECapital;LATIN CAPITAL LETTER E
00C9;EacuteCapital;LATIN CAPITAL LETTER E WITH ACUTE
0114;EbreveCapital;LATIN CAPITAL LETTER E WITH BREVE
011A;EcaronCapital;LATIN CAPITAL LETTER E WITH CARON
00CA;EcircumflexCapital;LATIN CAPITAL LETTER E WITH CIRCUMFLEX
00CB;EdieresisCapital;LATIN CAPITAL LETTER E WITH DIAERESIS
0116;EdotaccentCapital;LATIN CAPITAL LETTER E WITH DOT ABOVE
00C8;EgraveCapital;LATIN CAPITAL LETTER E WITH GRAVE
0112;EmacronCapital;LATIN CAPITAL LETTER E WITH MACRON
014A;EngCapital;LATIN CAPITAL LETTER ENG
0118;EogonekCapital;LATIN CAPITAL LETTER E WITH OGONEK
0395;EpsilonCapital;GREEK CAPITAL LETTER EPSILON
0388;EpsilontonosCapital;GREEK CAPITAL LETTER EPSILON WITH TONOS
0397;EtaCapital;GREEK CAPITAL LETTER ETA
0389;EtatonosCapital;GREEK CAPITAL LETTER ETA WITH TONOS
00D0;EthCapital;LATIN CAPITAL LETTER ETH
20AC;Euro;EURO SIGN
0046;FCapital;LATIN CAPITAL LETTER F
0047;GCapital;LATIN CAPITAL LETTER G
0393;GammaCapital;GREEK CAPITAL LETTER GAMMA
011E;GbreveCapital;LATIN CAPITAL LETTER G WITH BREVE
01E6;GcaronCapital;LATIN CAPITAL LETTER G WITH CARON
011C;GcircumflexCapital;LATIN CAPITAL LETTER G WITH CIRCUMFLEX
0120;GdotaccentCapital;LATIN CAPITAL LETTER G WITH DOT ABOVE
0048;HCapital;LATIN CAPITAL LETTER H
25CF;H18533;BLACK CIRCLE
25AA;H18543;BLACK SMALL SQUARE
25AB;H18551;WHITE SMALL SQUARE
25A1;H22073;WHITE SQUARE
0126;HbarCapital;LATIN CAPITAL LETTER H WITH STROKE
0124;HcircumflexCapital;LATIN CAPITAL LETTER H WITH CIRCUMFLEX
0049;ICapital;LATIN CAPITAL LETTER I
0132;IJCapital;LATIN CAPITAL LIGATURE IJ
00CD;IacuteCapital;LATIN CAPITAL LETTER I WITH ACUTE
012C;IbreveCapital;LATIN CAPITAL LETTER I WITH BREVE
00CE;IcircumflexCapital;LATIN CAPITAL LETTER I WITH CIRCUMFLEX
00CF;IdieresisCapital;LATIN CAPITAL LETTER I WITH DIAERESIS
0130;IdotaccentCapital;LATIN CAPITAL LETTER I WITH DOT ABOVE
2111;Ifraktur;BLACK-CapitalLETTER CAPITAL I
00CC;IgraveCapital;LATIN CAPITAL LETTER I WITH GRAVE
012A;ImacronCapital;LATIN CAPITAL LETTER I WITH MACRON
012E;IogonekCapital;LATIN CAPITAL LETTER I WITH OGONEK
0399;IotaCapital;GREEK CAPITAL LETTER IOTA
03AA;IotadieresisCapital;GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
038A;IotatonosCapital;GREEK CAPITAL LETTER IOTA WITH TONOS
0128;ItildeCapital;LATIN CAPITAL LETTER I WITH TILDE
004A;JCapital;LATIN CAPITAL LETTER J
0134;JcircumflexCapital;LATIN CAPITAL LETTER J WITH CIRCUMFLEX
004B;KCapital;LATIN CAPITAL LETTER K
039A;KappaCapital;GREEK CAPITAL LETTER KAPPA
004C;LCapital;LATIN CAPITAL LETTER L
0139;LacuteCapital;LATIN CAPITAL LETTER L WITH ACUTE
039B;LambdaCapital;GREEK CAPITAL LETTER LAMDA
013D;LcaronCapital;LATIN CAPITAL LETTER L WITH CARON
013F;LdotCapital;LATIN CAPITAL LETTER L WITH MIDDLE DOT
0141;LslashCapital;LATIN CAPITAL LETTER L WITH STROKE
004D;MCapital;LATIN CAPITAL LETTER M
039C;MuCapital;GREEK CAPITAL LETTER MU
004E;NCapital;LATIN CAPITAL LETTER N
0143;NacuteCapital;LATIN CAPITAL LETTER N WITH ACUTE
0147;NcaronCapital;LATIN CAPITAL LETTER N WITH CARON
00D1;NtildeCapital;LATIN CAPITAL LETTER N WITH TILDE
039D;NuCapital;GREEK CAPITAL LETTER NU
004F;OCapital;LATIN CAPITAL LETTER O
0152;OECapital;LATIN CAPITAL LIGATURE OE
00D3;OacuteCapital;LATIN CAPITAL LETTER O WITH ACUTE
014E;ObreveCapital;LATIN CAPITAL LETTER O WITH BREVE
00D4;OcircumflexCapital;LATIN CAPITAL LETTER O WITH CIRCUMFLEX
00D6;OdieresisCapital;LATIN CAPITAL LETTER O WITH DIAERESIS
00D2;OgraveCapital;LATIN CAPITAL LETTER O WITH GRAVE
01A0;OhornCapital;LATIN CAPITAL LETTER O WITH HORN
0150;OhungarumlautCapital;LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
014C;OmacronCapital;LATIN CAPITAL LETTER O WITH MACRON
2126;Omega;OHM SIGN
038F;OmegatonosCapital;GREEK CAPITAL LETTER OMEGA WITH TONOS
039F;OmicronCapital;GREEK CAPITAL LETTER OMICRON
038C;OmicrontonosCapital;GREEK CAPITAL LETTER OMICRON WITH TONOS
00D8;OslashCapital;LATIN CAPITAL LETTER O WITH STROKE
01FE;OslashacuteCapital;LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
00D5;OtildeCapital;LATIN CAPITAL LETTER O WITH TILDE
0050;PCapital;LATIN CAPITAL LETTER P
03A6;PhiCapital;GREEK CAPITAL LETTER PHI
03A0;PiCapital;GREEK CAPITAL LETTER PI
03A8;PsiCapital;GREEK CAPITAL LETTER PSI
0051;QCapital;LATIN CAPITAL LETTER Q
0052;RCapital;LATIN CAPITAL LETTER R
0154;RacuteCapital;LATIN CAPITAL LETTER R WITH ACUTE
0158;RcaronCapital;LATIN CAPITAL LETTER R WITH CARON
211C;Rfraktur;BLACK-CapitalLETTER CAPITAL R
03A1;RhoCapital;GREEK CAPITAL LETTER RHO
0053;SCapital;LATIN CAPITAL LETTER S
250C;SF010000;BOX DRAWINGS LIGHT DOWN AND RIGHT
2514;SF020000;BOX DRAWINGS LIGHT UP AND RIGHT
2510;SF030000;BOX DRAWINGS LIGHT DOWN AND LEFT
2518;SF040000;BOX DRAWINGS LIGHT UP AND LEFT
253C;SF050000;BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
252C;SF060000;BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
2534;SF070000;BOX DRAWINGS LIGHT UP AND HORIZONTAL
251C;SF080000;BOX DRAWINGS LIGHT VERTICAL AND RIGHT
2524;SF090000;BOX DRAWINGS LIGHT VERTICAL AND LEFT
2500;SF100000;BOX DRAWINGS LIGHT HORIZONTAL
2502;SF110000;BOX DRAWINGS LIGHT VERTICAL
2561;SF190000;BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
2562;SF200000;BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
2556;SF210000;BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
2555;SF220000;BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
2563;SF230000;BOX DRAWINGS DOUBLE VERTICAL AND LEFT
2551;SF240000;BOX DRAWINGS DOUBLE VERTICAL
2557;SF250000;BOX DRAWINGS DOUBLE DOWN AND LEFT
255D;SF260000;BOX DRAWINGS DOUBLE UP AND LEFT
255C;SF270000;BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
255B;SF280000;BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
255E;SF360000;BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
255F;SF370000;BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
255A;SF380000;BOX DRAWINGS DOUBLE UP AND RIGHT
2554;SF390000;BOX DRAWINGS DOUBLE DOWN AND RIGHT
2569;SF400000;BOX DRAWINGS DOUBLE UP AND HORIZONTAL
2566;SF410000;BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
2560;SF420000;BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
2550;SF430000;BOX DRAWINGS DOUBLE HORIZONTAL
256C;SF440000;BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
2567;SF450000;BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
2568;SF460000;BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
2564;SF470000;BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
2565;SF480000;BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
2559;SF490000;BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
2558;SF500000;BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
2552;SF510000;BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
2553;SF520000;BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
256B;SF530000;BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
256A;SF540000;BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
015A;SacuteCapital;LATIN CAPITAL LETTER S WITH ACUTE
0160;ScaronCapital;LATIN CAPITAL LETTER S WITH CARON
015E;ScedillaCapital;LATIN CAPITAL LETTER S WITH CEDILLA
015C;ScircumflexCapital;LATIN CAPITAL LETTER S WITH CIRCUMFLEX
03A3;SigmaCapital;GREEK CAPITAL LETTER SIGMA
0054;TCapital;LATIN CAPITAL LETTER T
03A4;TauCapital;GREEK CAPITAL LETTER TAU
0166;TbarCapital;LATIN CAPITAL LETTER T WITH STROKE
0164;TcaronCapital;LATIN CAPITAL LETTER T WITH CARON
0398;ThetaCapital;GREEK CAPITAL LETTER THETA
00DE;ThornCapital;LATIN CAPITAL LETTER THORN
0055;UCapital;LATIN CAPITAL LETTER U
00DA;UacuteCapital;LATIN CAPITAL LETTER U WITH ACUTE
016C;UbreveCapital;LATIN CAPITAL LETTER U WITH BREVE
00DB;UcircumflexCapital;LATIN CAPITAL LETTER U WITH CIRCUMFLEX
00DC;UdieresisCapital;LATIN CAPITAL LETTER U WITH DIAERESIS
00D9;UgraveCapital;LATIN CAPITAL LETTER U WITH GRAVE
01AF;UhornCapital;LATIN CAPITAL LETTER U WITH HORN
0170;UhungarumlautCapital;LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
016A;UmacronCapital;LATIN CAPITAL LETTER U WITH MACRON
0172;UogonekCapital;LATIN CAPITAL LETTER U WITH OGONEK
03A5;UpsilonCapital;GREEK CAPITAL LETTER UPSILON
03D2;Upsilon1;GREEK UPSILON WITH HOOK SYMBOL
03AB;UpsilondieresisCapital;GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
038E;UpsilontonosCapital;GREEK CAPITAL LETTER UPSILON WITH TONOS
016E;UringCapital;LATIN CAPITAL LETTER U WITH RING ABOVE
0168;UtildeCapital;LATIN CAPITAL LETTER U WITH TILDE
0056;VCapital;LATIN CAPITAL LETTER V
0057;WCapital;LATIN CAPITAL LETTER W
1E82;WacuteCapital;LATIN CAPITAL LETTER W WITH ACUTE
0174;WcircumflexCapital;LATIN CAPITAL LETTER W WITH CIRCUMFLEX
1E84;WdieresisCapital;LATIN CAPITAL LETTER W WITH DIAERESIS
1E80;WgraveCapital;LATIN CAPITAL LETTER W WITH GRAVE
0058;XCapital;LATIN CAPITAL LETTER X
039E;XiCapital;GREEK CAPITAL LETTER XI
0059;YCapital;LATIN CAPITAL LETTER Y
00DD;YacuteCapital;LATIN CAPITAL LETTER Y WITH ACUTE
0176;YcircumflexCapital;LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
0178;YdieresisCapital;LATIN CAPITAL LETTER Y WITH DIAERESIS
1EF2;YgraveCapital;LATIN CAPITAL LETTER Y WITH GRAVE
005A;ZCapital;LATIN CAPITAL LETTER Z
0179;ZacuteCapital;LATIN CAPITAL LETTER Z WITH ACUTE
017D;ZcaronCapital;LATIN CAPITAL LETTER Z WITH CARON
017B;ZdotaccentCapital;LATIN CAPITAL LETTER Z WITH DOT ABOVE
0396;ZetaCapital;GREEK CAPITAL LETTER ZETA
0061;a;LATIN SMALL LETTER A
00E1;aacute;LATIN SMALL LETTER A WITH ACUTE
0103;abreve;LATIN SMALL LETTER A WITH BREVE
00E2;acircumflex;LATIN SMALL LETTER A WITH CIRCUMFLEX
00B4;acute;ACUTE ACCENT
0301;acutecomb;COMBINING ACUTE ACCENT
00E4;adieresis;LATIN SMALL LETTER A WITH DIAERESIS
00E6;ae;LATIN SMALL LETTER AE
01FD;aeacute;LATIN SMALL LETTER AE WITH ACUTE
00E0;agrave;LATIN SMALL LETTER A WITH GRAVE
2135;aleph;ALEF SYMBOL
03B1;alpha;GREEK SMALL LETTER ALPHA
03AC;alphatonos;GREEK SMALL LETTER ALPHA WITH TONOS
0101;amacron;LATIN SMALL LETTER A WITH MACRON
0026;ampersand;AMPERSAND
2220;angle;ANGLE
2329;angleleft;LEFT-POINTING ANGLE BRACKET
232A;angleright;RIGHT-POINTING ANGLE BRACKET
0387;anoteleia;GREEK ANO TELEIA
0105;aogonek;LATIN SMALL LETTER A WITH OGONEK
2248;approxequal;ALMOST EQUAL TO
00E5;aring;LATIN SMALL LETTER A WITH RING ABOVE
01FB;aringacute;LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
2194;arrowboth;LEFT RIGHT ARROW
21D4;arrowdblboth;LEFT RIGHT DOUBLE ARROW
21D3;arrowdbldown;DOWNWARDS DOUBLE ARROW
21D0;arrowdblleft;LEFTWARDS DOUBLE ARROW
21D2;arrowdblright;RIGHTWARDS DOUBLE ARROW
21D1;arrowdblup;UPWARDS DOUBLE ARROW
2193;arrowdown;DOWNWARDS ARROW
2190;arrowleft;LEFTWARDS ARROW
2192;arrowright;RIGHTWARDS ARROW
2191;arrowup;UPWARDS ARROW
2195;arrowupdn;UP DOWN ARROW
21A8;arrowupdnbse;UP DOWN ARROW WITH BASE
005E;asciicircum;CIRCUMFLEX ACCENT
007E;asciitilde;TILDE
002A;asterisk;ASTERISK
2217;asteriskmath;ASTERISK OPERATOR
0040;at;COMMERCIAL AT
00E3;atilde;LATIN SMALL LETTER A WITH TILDE
0062;b;LATIN SMALL LETTER B
005C;backslash;REVERSE SOLIDUS
007C;bar;VERTICAL LINE
03B2;beta;GREEK SMALL LETTER BETA
2588;block;FULL BLOCK
007B;braceleft;LEFT CURLY BRACKET
007D;braceright;RIGHT CURLY BRACKET
005B;bracketleft;LEFT SQUARE BRACKET
005D;bracketright;RIGHT SQUARE BRACKET
02D8;breve;BREVE
00A6;brokenbar;BROKEN BAR
2022;bullet;BULLET
0063;c;LATIN SMALL LETTER C
0107;cacute;LATIN SMALL LETTER C WITH ACUTE
02C7;caron;CARON
21B5;carriagereturn;DOWNWARDS ARROW WITH CORNER LEFTWARDS
010D;ccaron;LATIN SMALL LETTER C WITH CARON
00E7;ccedilla;LATIN SMALL LETTER C WITH CEDILLA
0109;ccircumflex;LATIN SMALL LETTER C WITH CIRCUMFLEX
010B;cdotaccent;LATIN SMALL LETTER C WITH DOT ABOVE
00B8;cedilla;CEDILLA
00A2;cent;CENT SIGN
03C7;chi;GREEK SMALL LETTER CHI
25CB;circle;WHITE CIRCLE
2297;circlemultiply;CIRCLED TIMES
2295;circleplus;CIRCLED PLUS
02C6;circumflex;MODIFIER LETTER CIRCUMFLEX ACCENT
2663;club;BLACK CLUB SUIT
003A;colon;COLON
20A1;colonmonetary;COLON SIGN
002C;comma;COMMA
2245;congruent;APPROXIMATELY EQUAL TO
00A9;copyright;COPYRIGHT SIGN
00A4;currency;CURRENCY SIGN
0064;d;LATIN SMALL LETTER D
2020;dagger;DAGGER
2021;daggerdbl;DOUBLE DAGGER
010F;dcaron;LATIN SMALL LETTER D WITH CARON
0111;dcroat;LATIN SMALL LETTER D WITH STROKE
00B0;degree;DEGREE SIGN
03B4;delta;GREEK SMALL LETTER DELTA
2666;diamond;BLACK DIAMOND SUIT
00A8;dieresis;DIAERESIS
0385;dieresistonos;GREEK DIALYTIKA TONOS
00F7;divide;DIVISION SIGN
2593;dkshade;DARK SHADE
2584;dnblock;LOWER HALF BLOCK
0024;dollar;DOLLAR SIGN
20AB;dong;DONG SIGN
02D9;dotaccent;DOT ABOVE
0323;dotbelowcomb;COMBINING DOT BELOW
0131;dotlessi;LATIN SMALL LETTER DOTLESS I
22C5;dotmath;DOT OPERATOR
0065;e;LATIN SMALL LETTER E
00E9;eacute;LATIN SMALL LETTER E WITH ACUTE
0115;ebreve;LATIN SMALL LETTER E WITH BREVE
011B;ecaron;LATIN SMALL LETTER E WITH CARON
00EA;ecircumflex;LATIN SMALL LETTER E WITH CIRCUMFLEX
00EB;edieresis;LATIN SMALL LETTER E WITH DIAERESIS
0117;edotaccent;LATIN SMALL LETTER E WITH DOT ABOVE
00E8;egrave;LATIN SMALL LETTER E WITH GRAVE
0038;eight;DIGIT EIGHT
2208;element;ELEMENT OF
2026;ellipsis;HORIZONTAL ELLIPSIS
0113;emacron;LATIN SMALL LETTER E WITH MACRON
2014;emdash;EM DASH
2205;emptyset;EMPTY SET
2013;endash;EN DASH
014B;eng;LATIN SMALL LETTER ENG
0119;eogonek;LATIN SMALL LETTER E WITH OGONEK
03B5;epsilon;GREEK SMALL LETTER EPSILON
03AD;epsilontonos;GREEK SMALL LETTER EPSILON WITH TONOS
003D;equal;EQUALS SIGN
2261;equivalence;IDENTICAL TO
212E;estimated;ESTIMATED SYMBOL
03B7;eta;GREEK SMALL LETTER ETA
03AE;etatonos;GREEK SMALL LETTER ETA WITH TONOS
00F0;eth;LATIN SMALL LETTER ETH
0021;exclam;EXCLAMATION MARK
203C;exclamdbl;DOUBLE EXCLAMATION MARK
00A1;exclamdown;INVERTED EXCLAMATION MARK
2203;existential;THERE EXISTS
0066;f;LATIN SMALL LETTER F
2640;female;FEMALE SIGN
2012;figuredash;FIGURE DASH
25A0;filledbox;BLACK SQUARE
25AC;filledrect;BLACK RECTANGLE
0035;five;DIGIT FIVE
215D;fiveeighths;VULGAR FRACTION FIVE EIGHTHS
0192;florin;LATIN SMALL LETTER F WITH HOOK
0034;four;DIGIT FOUR
2044;fraction;FRACTION SLASH
20A3;franc;FRENCH FRANC SIGN
0067;g;LATIN SMALL LETTER G
03B3;gamma;GREEK SMALL LETTER GAMMA
011F;gbreve;LATIN SMALL LETTER G WITH BREVE
01E7;gcaron;LATIN SMALL LETTER G WITH CARON
011D;gcircumflex;LATIN SMALL LETTER G WITH CIRCUMFLEX
0121;gdotaccent;LATIN SMALL LETTER G WITH DOT ABOVE
00DF;germandbls;LATIN SMALL LETTER SHARP S
2207;gradient;NABLA
0060;grave;GRAVE ACCENT
0300;gravecomb;COMBINING GRAVE ACCENT
003E;greater;GREATER-THAN SIGN
2265;greaterequal;GREATER-THAN OR EQUAL TO
00AB;guillemotleft;LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
00BB;guillemotright;RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
2039;guilsinglleft;SINGLE LEFT-POINTING ANGLE QUOTATION MARK
203A;guilsinglright;SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
0068;h;LATIN SMALL LETTER H
0127;hbar;LATIN SMALL LETTER H WITH STROKE
0125;hcircumflex;LATIN SMALL LETTER H WITH CIRCUMFLEX
2665;heart;BLACK HEART SUIT
0309;hookabovecomb;COMBINING HOOK ABOVE
2302;house;HOUSE
02DD;hungarumlaut;DOUBLE ACUTE ACCENT
002D;hyphen;HYPHEN-MINUS
0069;i;LATIN SMALL LETTER I
00ED;iacute;LATIN SMALL LETTER I WITH ACUTE
012D;ibreve;LATIN SMALL LETTER I WITH BREVE
00EE;icircumflex;LATIN SMALL LETTER I WITH CIRCUMFLEX
00EF;idieresis;LATIN SMALL LETTER I WITH DIAERESIS
00EC;igrave;LATIN SMALL LETTER I WITH GRAVE
0133;ij;LATIN SMALL LIGATURE IJ
012B;imacron;LATIN SMALL LETTER I WITH MACRON
221E;infinity;INFINITY
222B;integral;INTEGRAL
2321;integralbt;BOTTOM HALF INTEGRAL
2320;integraltp;TOP HALF INTEGRAL
2229;intersection;INTERSECTION
25D8;invbullet;INVERSE BULLET
25D9;invcircle;INVERSE WHITE CIRCLE
263B;invsmileface;BLACK SMILING FACE
012F;iogonek;LATIN SMALL LETTER I WITH OGONEK
03B9;iota;GREEK SMALL LETTER IOTA
03CA;iotadieresis;GREEK SMALL LETTER IOTA WITH DIALYTIKA
0390;iotadieresistonos;GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
03AF;iotatonos;GREEK SMALL LETTER IOTA WITH TONOS
0129;itilde;LATIN SMALL LETTER I WITH TILDE
006A;j;LATIN SMALL LETTER J
0135;jcircumflex;LATIN SMALL LETTER J WITH CIRCUMFLEX
006B;k;LATIN SMALL LETTER K
03BA;kappa;GREEK SMALL LETTER KAPPA
0138;kgreenlandic;LATIN SMALL LETTER KRA
006C;l;LATIN SMALL LETTER L
013A;lacute;LATIN SMALL LETTER L WITH ACUTE
03BB;lambda;GREEK SMALL LETTER LAMDA
013E;lcaron;LATIN SMALL LETTER L WITH CARON
0140;ldot;LATIN SMALL LETTER L WITH MIDDLE DOT
003C;less;LESS-THAN SIGN
2264;lessequal;LESS-THAN OR EQUAL TO
258C;lfblock;LEFT HALF BLOCK
20A4;lira;LIRA SIGN
2227;logicaland;LOGICAL AND
00AC;logicalnot;NOT SIGN
2228;logicalor;LOGICAL OR
017F;longs;LATIN SMALL LETTER LONG S
25CA;lozenge;LOZENGE
0142;lslash;LATIN SMALL LETTER L WITH STROKE
2591;ltshade;LIGHT SHADE
006D;m;LATIN SMALL LETTER M
00AF;macron;MACRON
2642;male;MALE SIGN
2212;minus;MINUS SIGN
2032;minute;PRIME
00B5;mu;MICRO SIGN
00D7;multiply;MULTIPLICATION SIGN
266A;musicalnote;EIGHTH NOTE
266B;musicalnotedbl;BEAMED EIGHTH NOTES
006E;n;LATIN SMALL LETTER N
0144;nacute;LATIN SMALL LETTER N WITH ACUTE
0149;napostrophe;LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
0148;ncaron;LATIN SMALL LETTER N WITH CARON
0039;nine;DIGIT NINE
2209;notelement;NOT AN ELEMENT OF
2260;notequal;NOT EQUAL TO
2284;notsubset;NOT A SUBSET OF
00F1;ntilde;LATIN SMALL LETTER N WITH TILDE
03BD;nu;GREEK SMALL LETTER NU
0023;numbersign;NUMBER SIGN
006F;o;LATIN SMALL LETTER O
00F3;oacute;LATIN SMALL LETTER O WITH ACUTE
014F;obreve;LATIN SMALL LETTER O WITH BREVE
00F4;ocircumflex;LATIN SMALL LETTER O WITH CIRCUMFLEX
00F6;odieresis;LATIN SMALL LETTER O WITH DIAERESIS
0153;oe;LATIN SMALL LIGATURE OE
02DB;ogonek;OGONEK
00F2;ograve;LATIN SMALL LETTER O WITH GRAVE
01A1;ohorn;LATIN SMALL LETTER O WITH HORN
0151;ohungarumlaut;LATIN SMALL LETTER O WITH DOUBLE ACUTE
014D;omacron;LATIN SMALL LETTER O WITH MACRON
03C9;omega;GREEK SMALL LETTER OMEGA
03D6;omega1;GREEK PI SYMBOL
03CE;omegatonos;GREEK SMALL LETTER OMEGA WITH TONOS
03BF;omicron;GREEK SMALL LETTER OMICRON
03CC;omicrontonos;GREEK SMALL LETTER OMICRON WITH TONOS
0031;one;DIGIT ONE
2024;onedotenleader;ONE DOT LEADER
215B;oneeighth;VULGAR FRACTION ONE EIGHTH
00BD;onehalf;VULGAR FRACTION ONE HALF
00BC;onequarter;VULGAR FRACTION ONE QUARTER
2153;onethird;VULGAR FRACTION ONE THIRD
25E6;openbullet;WHITE BULLET
00AA;ordfeminine;FEMININE ORDINAL INDICATOR
00BA;ordmasculine;MASCULINE ORDINAL INDICATOR
221F;orthogonal;RIGHT ANGLE
00F8;oslash;LATIN SMALL LETTER O WITH STROKE
01FF;oslashacute;LATIN SMALL LETTER O WITH STROKE AND ACUTE
00F5;otilde;LATIN SMALL LETTER O WITH TILDE
0070;p;LATIN SMALL LETTER P
00B6;paragraph;PILCROW SIGN
0028;parenleft;LEFT PARENTHESIS
0029;parenright;RIGHT PARENTHESIS
2202;partialdiff;PARTIAL DIFFERENTIAL
0025;percent;PERCENT SIGN
002E;period;FULL STOP
00B7;periodcentered;MIDDLE DOT
22A5;perpendicular;UP TACK
2030;perthousand;PER MILLE SIGN
20A7;peseta;PESETA SIGN
03C6;phi;GREEK SMALL LETTER PHI
03D5;phi1;GREEK PHI SYMBOL
03C0;pi;GREEK SMALL LETTER PI
002B;plus;PLUS SIGN
00B1;plusminus;PLUS-MINUS SIGN
211E;prescription;PRESCRIPTION TAKE
220F;product;N-ARY PRODUCT
2282;propersubset;SUBSET OF
2283;propersuperset;SUPERSET OF
221D;proportional;PROPORTIONAL TO
03C8;psi;GREEK SMALL LETTER PSI
0071;q;LATIN SMALL LETTER Q
003F;question;QUESTION MARK
00BF;questiondown;INVERTED QUESTION MARK
0022;quotedbl;QUOTATION MARK
201E;quotedblbase;DOUBLE LOW-9 QUOTATION MARK
201C;quotedblleft;LEFT DOUBLE QUOTATION MARK
201D;quotedblright;RIGHT DOUBLE QUOTATION MARK
2018;quoteleft;LEFT SINGLE QUOTATION MARK
201B;quotereversed;SINGLE HIGH-REVERSED-9 QUOTATION MARK
2019;quoteright;RIGHT SINGLE QUOTATION MARK
201A;quotesinglbase;SINGLE LOW-9 QUOTATION MARK
0027;quotesingle;APOSTROPHE
0072;r;LATIN SMALL LETTER R
0155;racute;LATIN SMALL LETTER R WITH ACUTE
221A;radical;SQUARE ROOT
0159;rcaron;LATIN SMALL LETTER R WITH CARON
2286;reflexsubset;SUBSET OF OR EQUAL TO
2287;reflexsuperset;SUPERSET OF OR EQUAL TO
00AE;registered;REGISTERED SIGN
2310;revlogicalnot;REVERSED NOT SIGN
03C1;rho;GREEK SMALL LETTER RHO
02DA;ring;RING ABOVE
2590;rtblock;RIGHT HALF BLOCK
0073;s;LATIN SMALL LETTER S
015B;sacute;LATIN SMALL LETTER S WITH ACUTE
0161;scaron;LATIN SMALL LETTER S WITH CARON
015F;scedilla;LATIN SMALL LETTER S WITH CEDILLA
015D;scircumflex;LATIN SMALL LETTER S WITH CIRCUMFLEX
2033;second;DOUBLE PRIME
00A7;section;SECTION SIGN
003B;semicolon;SEMICOLON
0037;seven;DIGIT SEVEN
215E;seveneighths;VULGAR FRACTION SEVEN EIGHTHS
2592;shade;MEDIUM SHADE
03C3;sigma;GREEK SMALL LETTER SIGMA
03C2;sigma1;GREEK SMALL LETTER FINAL SIGMA
223C;similar;TILDE OPERATOR
0036;six;DIGIT SIX
002F;slash;SOLIDUS
263A;smileface;WHITE SMILING FACE
0020;space;SPACE
2660;spade;BLACK SPADE SUIT
00A3;sterling;POUND SIGN
220B;suchthat;CONTAINS AS MEMBER
2211;summation;N-ARY SUMMATION
263C;sun;WHITE SUN WITH RAYS
0074;t;LATIN SMALL LETTER T
03C4;tau;GREEK SMALL LETTER TAU
0167;tbar;LATIN SMALL LETTER T WITH STROKE
0165;tcaron;LATIN SMALL LETTER T WITH CARON
2234;therefore;THEREFORE
03B8;theta;GREEK SMALL LETTER THETA
03D1;theta1;GREEK THETA SYMBOL
00FE;thorn;LATIN SMALL LETTER THORN
0033;three;DIGIT THREE
215C;threeeighths;VULGAR FRACTION THREE EIGHTHS
00BE;threequarters;VULGAR FRACTION THREE QUARTERS
02DC;tilde;SMALL TILDE
0303;tildecomb;COMBINING TILDE
0384;tonos;GREEK TONOS
2122;trademark;TRADE MARK SIGN
25BC;triagdn;BLACK DOWN-POINTING TRIANGLE
25C4;triaglf;BLACK LEFT-POINTING POINTER
25BA;triagrt;BLACK RIGHT-POINTING POINTER
25B2;triagup;BLACK UP-POINTING TRIANGLE
0032;two;DIGIT TWO
2025;twodotenleader;TWO DOT LEADER
2154;twothirds;VULGAR FRACTION TWO THIRDS
0075;u;LATIN SMALL LETTER U
00FA;uacute;LATIN SMALL LETTER U WITH ACUTE
016D;ubreve;LATIN SMALL LETTER U WITH BREVE
00FB;ucircumflex;LATIN SMALL LETTER U WITH CIRCUMFLEX
00FC;udieresis;LATIN SMALL LETTER U WITH DIAERESIS
00F9;ugrave;LATIN SMALL LETTER U WITH GRAVE
01B0;uhorn;LATIN SMALL LETTER U WITH HORN
0171;uhungarumlaut;LATIN SMALL LETTER U WITH DOUBLE ACUTE
016B;umacron;LATIN SMALL LETTER U WITH MACRON
005F;underscore;LOW LINE
2017;underscoredbl;DOUBLE LOW LINE
222A;union;UNION
2200;universal;FOR ALL
0173;uogonek;LATIN SMALL LETTER U WITH OGONEK
2580;upblock;UPPER HALF BLOCK
03C5;upsilon;GREEK SMALL LETTER UPSILON
03CB;upsilondieresis;GREEK SMALL LETTER UPSILON WITH DIALYTIKA
03B0;upsilondieresistonos;GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
03CD;upsilontonos;GREEK SMALL LETTER UPSILON WITH TONOS
016F;uring;LATIN SMALL LETTER U WITH RING ABOVE
0169;utilde;LATIN SMALL LETTER U WITH TILDE
0076;v;LATIN SMALL LETTER V
0077;w;LATIN SMALL LETTER W
1E83;wacute;LATIN SMALL LETTER W WITH ACUTE
0175;wcircumflex;LATIN SMALL LETTER W WITH CIRCUMFLEX
1E85;wdieresis;LATIN SMALL LETTER W WITH DIAERESIS
2118;weierstrass;CapitalSCRIPT CAPITAL P
1E81;wgrave;LATIN SMALL LETTER W WITH GRAVE
0078;x;LATIN SMALL LETTER X
03BE;xi;GREEK SMALL LETTER XI
0079;y;LATIN SMALL LETTER Y
00FD;yacute;LATIN SMALL LETTER Y WITH ACUTE
0177;ycircumflex;LATIN SMALL LETTER Y WITH CIRCUMFLEX
00FF;ydieresis;LATIN SMALL LETTER Y WITH DIAERESIS
00A5;yen;YEN SIGN
1EF3;ygrave;LATIN SMALL LETTER Y WITH GRAVE
007A;z;LATIN SMALL LETTER Z
017A;zacute;LATIN SMALL LETTER Z WITH ACUTE
017E;zcaron;LATIN SMALL LETTER Z WITH CARON
017C;zdotaccent;LATIN SMALL LETTER Z WITH DOT ABOVE
0030;zero;DIGIT ZERO
03B6;zeta;GREEK SMALL LETTER ZETA
""";
    public static Dictionary<int, string> Names = [];

    public static void PrepareNames()
    {
        string[] lines = raw.Split(new[] {"\n", "\r\n"}, StringSplitOptions.None);
        foreach (string line in lines)
        {
            string[] words = line.Split(';');
            Names[UInt16.Parse(words[0], System.Globalization.NumberStyles.HexNumber)] = words[1];
        }
    }        
}